# Generated by Django 3.1.6 on 2021-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('rate', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('price', models.IntegerField()),
                ('time', models.IntegerField(verbose_name='زمان لازم')),
                ('pop_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='foods/')),
                ('type_food', models.CharField(choices=[('breakfast', 'صبحانه'), ('drinks', 'نوشیدنی ها'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='lunch', max_length=10, verbose_name='نوع غذا')),
            ],
        ),
    ]
