# Generated by Django 3.1.6 on 2022-11-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210319_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.RenameField(
            model_name='food',
            old_name='pop_date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakefast', 'صبحانه'), ('drinks', 'نوشیدنی'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
