# Generated by Django 3.1.6 on 2022-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20221201_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.RenameField(
            model_name='food',
            old_name='pub_date',
            new_name='pop_date',
        ),
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('drinks', 'نوشیدنی ها'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='lunch', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
