# Generated by Django 3.1.6 on 2021-03-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210221_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogs', to='blog.tag', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل کاربر')),
                ('message', models.TextField(verbose_name='متن')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blog.blog', verbose_name='مقاله')),
            ],
        ),
    ]
